### ISSUE TITLE
React shows warning when using `maybe` + None

### ISSUE THREAD

**Issue by jchavarri** [ml-in-barcelona/jsoo-react#130]
When using a prop with `maybe` and passing `None` (e.g. `maybe className None`), React.js will emit a warning:

```
Warning: Invalid attribute name: ``
    in div
```

This happens in ml syntax:

https://github.com/ml-in-barcelona/jsoo-react/blob/d3924adb125a8a7fadb8c2535486127c9b05c1fa/test/test_ml.ml#L704

And Reason syntax:

https://github.com/ml-in-barcelona/jsoo-react/blob/d3924adb125a8a7fadb8c2535486127c9b05c1fa/test/test_reason.re#L1156

I tried using any other string like `_` or `_unused` and in those cases React does not complain 🤔 Another alternative would be to conditionally push to the array.

**Comment by glennsl** [comment]
Perhaps if we use `any "" Js.undefined`, React will ignore it?

**Comment by jchavarri** [comment]
The issue is with the prop name, not the value. I just tried `{undefined: undefined}` and it works 🤣 

https://codesandbox.io/s/spring-framework-enqjl?file=/src/App.js

**Comment by glennsl** [comment]
I don't get any warning with `{'': undefined}` either:

https://codesandbox.io/s/compassionate-glade-iep03?file=/src/App.js

**Comment by jchavarri** [comment]
Ah, you're right. 😕
