### ISSUE TITLE
using jsoo-react.ppx with ppx_deriving causes compilation error

### ISSUE THREAD

**Issue by joprice** [ml-in-barcelona/jsoo-react#132]
When I try to use jsoo-react.ppx and ppx_deriving together, I get a type error.

```
File "src/react-test/data.ml", line 1, characters 0-50:
1 | type user = { id : int } [@@deriving yojson, show]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value pp_user
```

(I'm trying out the new bucklescript-tea style ocaml dsl, so I'm not even sure I need the `%component` extension right now as this is the first time I'm trying the library).

**Comment by jchavarri** [comment]
small repro:

```
let rec pp_user = 2
```

gets converted into 

```
let pp_user = 2
```

after jsoo-react ppx passes.
