### ISSUE TITLE
Hooks that watch values use inconvenient equality semantics

### ISSUE THREAD

**Issue by glennsl** [ml-in-barcelona/jsoo-react#153]
Hooks that watch values for triggering updates, such as `useEffectN`, `useMemoN` etc., use the equality semantics of JavaScript instead of OCaml. And since OCaml values are often "block" values, represented as arrays in JavaScript, this will almost always be reference equality, and almost never what you want. The only values that would conform to expectations, I think, are `int`s, `float`s and `bool`s. 

We ought to look into how we can offer the equality semantics users expect.

**Comment by jchavarri** [comment]
@glennsl I consider this fixed by #154, please reopen if that's not the case.

Thanks for your work on this! 🎉
