### ISSUE TITLE
Svg.rect x/y attributes ?

### ISSUE THREAD

**Issue by zeroexcuses** [ml-in-barcelona/jsoo-react#176]
How do we set the x/y attributes on Svg.rect ?

**Comment by benschinn** [comment]
It looks like `Svg.rect` has props `x` and `y`:
https://github.com/ml-in-barcelona/jsoo-react/blob/4cae40f36bb9f4b7980e9ca11e63a992b01d3a8f/ppx/html.ml#L1480-L1481

https://github.com/ml-in-barcelona/jsoo-react/blob/4cae40f36bb9f4b7980e9ca11e63a992b01d3a8f/ppx/html.ml#L2262

I haven't tested, but I imagine something like this:
```
open Svg;
module Prop = {
  include Html.Prop;
  include Svg.Prop;
};

React.Dom.render(
  <svg width="100" height="100">
    <rect y="20" x="20" width="60" height="60" />
  </svg>,
  Dom_html.element(c),
)
```
